#CIRCUITPY_WIFI_PASSWORD="!nt$l??!g$nt*"
#CIRCUITPY_WIFI_SSID="CEGEP IdO"

CIRCUITPY_WIFI_PASSWORD="2006phocus43"
CIRCUITPY_WIFI_SSID="thedealrock"

APIPOST="https://api.thingspeak.com/update?api_key=RYR1DFNR5NV3GIKV"